import { dbConnect } from "./api/mongo/route";
import { Nunito } from "next/font/google";
import "./globals.css";

const nunito = Nunito ({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
const conn = await dbConnect();
console.log(conn);
  return (
    <html lang="en">
      <body className={nunito.className}>{children}</body>
    </html>
  );
}
